### ISSUE TITLE
`cloud_datastore_emulator` script not `exec`ing into Java

### ISSUE THREAD

**Issue by remko** [googleapis/google-cloud-datastore#210] opened 2018-08-27 06:45 UTC
The `platform/cloud-datastore-emulator/cloud_datastore_emulator` script calls into `java` at the end of the script to start the datastore emulator, unnecessarily spawning a new child. This is causing some issues for me in my dev environment where the datastore emulator is not shut down properly.

Is it intentional to not `exec` into `java` at the end of the script?

**Comment by meredithslota** [comment] 2023-01-24 00:10
I ... actually can't find this file or reference. Closing as I cannot reproduce. @remko If you can find the reference again, please let me know!

**Closed by meredithslota** 2023-01-24 00:10 UTC
Labels: type: question, api: datastore
